# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 02:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_code', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='title',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='code',
            name='code_text',
            field=models.TextField(max_length=1000000, verbose_name='code'),
        ),
    ]
