# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 02:43
from __future__ import unicode_literals

from django.db import migrations, models
import post_code.models


class Migration(migrations.Migration):

    dependencies = [
        ('post_code', '0002_auto_20161024_0234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='code',
            name='id',
        ),
        migrations.AddField(
            model_name='code',
            name='hash_key',
            field=models.CharField(default=post_code.models.pkgen, editable=False, max_length=8, primary_key=True, serialize=False, unique=True),
        ),
    ]
